
env_args:
    env: 'handyrl.envs.ahc008'
    #env: 'TicTacToe'
    #env: 'Geister'
    #env: 'HungryGeese'
    #env: 'handyrl.envs.parallel_tictactoe'  # specify by path

train_args:
    turn_based_training: False
    observation: False
    gamma: 0.5
    forward_steps: 16
    burn_in_steps: 0  # for RNNs
    compress_steps: 4
    entropy_regularization: 1.0e-1
    entropy_regularization_decay: 0.1
    update_episodes: 100
    batch_size: 16
    minimum_episodes: 16
    maximum_episodes: 64
    epochs: -1
    num_batchers: 3
    eval_rate: 0.1
    worker:
        num_parallel: 4
    lambda: 0.4
    policy_target: 'TD' # 'UPGO' 'VTRACE' 'TD' 'MC'
    value_target: 'TD' # 'VTRACE' 'TD' 'MC'
    eval:
        opponent: ['random']
    seed: 0
    restart_epoch: 0


worker_args:
    server_address: '35.192.152.246'
    num_parallel: 30
